[tool.coverage.run]
branch = true
source = [ "src" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = """
 --cov
 --cov-report html:'../../coverage/sistema-unidad-territorial/backend/html'
 --cov-report xml:'../../coverage/sistema-unidad-territorial/backend/coverage.xml'
 --html='../../reports/sistema-unidad-territorial/backend/unittests/html/index.html'
 --junitxml='../../reports/sistema-unidad-territorial/backend/unittests/junit.xml'
"""

[tool.poetry]
name = "sistema-unidad-territorial/backend"
version = "1.0.0"
description = "Backend del Sistema Unidad Territorial con FastAPI--packageName=src"
authors = [ ]
license = 'Proprietary'
readme = 'README.md'

  [[tool.poetry.packages]]
  include = "src"

  [tool.poetry.dependencies]
  python = ">=3.9,<3.14"
  alembic = "^1.16.4"
  sqlalchemy = "^2.0.43"
  psycopg = {version = "^3.2.1", extras = ["binary"]}
  python-dotenv = "^1.0.1"
  pytz = "^2025.2"
  pydantic = {extras = ["email"], version = "^2.11.7"}
  pydantic-settings = "^2.10.1"
  psycopg2 = "^2.9.10"
  fastapi = "^0.115.6"
  uvicorn = {version = "^0.34.0", extras = ["standard"]}
  python-jose = {version = "^3.3.0", extras = ["cryptography"]}
  passlib = {version = "^1.7.4", extras = ["bcrypt"]}
  bcrypt = "^4.0.0"
  python-multipart = "^0.0.20"
  authlib = "^1.4.0"
  httpx = "^0.28.1"
  asyncpg = "^0.30.0"
  requests = "^2.32.4"
  aiohttp = "^3.12.15"
  reportlab = "^4.4.4"
  pypdf2 = "^3.0.1"
  cryptography = "^43.0.0"
  twilio = "^9.8.6"

  [tool.poetry.group.dev.dependencies]
  autopep8 = "2.3.1"
  flake8 = "7.1.1"
  pytest = "8.3.4"
  pytest-sugar = "1.0.0"
  pytest-cov = "6.0.0"
  pytest-html = "4.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
