"""important changes

Revision ID: 5a69fdeb4f26
Revises: 
Create Date: 2025-10-13 22:37:52.106662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a69fdeb4f26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('title', sa.Text(), nullable=False, comment='News title'),
    sa.Column('body', sa.Text(), nullable=False, comment='News content'),
    sa.Column('visible_from', sa.DateTime(timezone=True), nullable=False, comment='Start of visibility period'),
    sa.Column('visible_until', sa.DateTime(timezone=True), nullable=True, comment='End of visibility period (optional)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant ID for multi-tenancy support (NOT NULL)'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.CheckConstraint('visible_until IS NULL OR visible_until > visible_from', name='ck_news_valid_dates'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('outbox',
    sa.Column('type', sa.Text(), nullable=False, comment='Message type: email, whatsapp, webhook, etc.'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Message data'),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False, comment='Processing status: pending, processing, processed, failed'),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False, comment='Number of delivery attempts'),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False, comment='Maximum delivery attempts before marking as failed'),
    sa.Column('next_attempt_at', postgresql.TIMESTAMP(), nullable=True, comment='Next delivery attempt timestamp'),
    sa.Column('processed_at', postgresql.TIMESTAMP(), nullable=True, comment='Timestamp when successfully processed'),
    sa.Column('dedupe_key', sa.Text(), nullable=True, comment='Deduplication key for idempotency'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.CheckConstraint("jsonb_typeof(payload) = 'object'", name='ck_outbox_payload_object'),
    sa.CheckConstraint("payload ? 'to'", name='ck_outbox_payload_has_to'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'processed', 'failed')", name='ck_outbox_status'),
    sa.CheckConstraint('attempts <= max_attempts', name='ck_outbox_attempts_limit'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Role name'),
    sa.Column('scope', sa.Enum('GLOBAL', 'TENANT', 'COMMUNITY', 'SYSTEM', name='role_scope_enum'), server_default='SYSTEM', nullable=False, comment='Role scope (SYSTEM, TENANT, COMMUNITY)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'scope', name='uq_role_name_scope'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('status_certificate',
    sa.Column('code', sa.String(length=20), nullable=False, comment='Código del estado de certificado'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Nombre descriptivo del estado'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción del estado'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Orden de visualización'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.PrimaryKeyConstraint('code', 'id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('status_membership',
    sa.Column('code', sa.String(length=20), nullable=False, comment='Código del estado de membresía'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Nombre descriptivo del estado'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción del estado'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Orden de visualización'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.PrimaryKeyConstraint('code', 'id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('status_project',
    sa.Column('code', sa.String(length=20), nullable=False, comment='Código del estado de proyecto'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Nombre descriptivo del estado'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción del estado'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Orden de visualización'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.PrimaryKeyConstraint('code', 'id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('status_registration',
    sa.Column('code', sa.String(length=20), nullable=False, comment='Código del estado de solicitud de registro'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Nombre descriptivo del estado'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción del estado'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Orden de visualización'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.PrimaryKeyConstraint('code', 'id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('status_reservation',
    sa.Column('code', sa.String(length=20), nullable=False, comment='Código del estado de reserva'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Nombre descriptivo del estado'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción del estado'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Orden de visualización'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.PrimaryKeyConstraint('code', 'id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('tenant_folio_seq',
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='ID del tenant'),
    sa.Column('last_folio', sa.Integer(), nullable=False, comment='Último folio emitido'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.PrimaryKeyConstraint('tenant_id', 'id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('tenants',
    sa.Column('name', sa.Text(), nullable=False, comment='Tenant name'),
    sa.Column('domain', sa.Text(), nullable=True, comment="Email domain for institutional emails (e.g., 'recoleta.cl')"),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('users',
    sa.Column('primary_email_id', sa.UUID(), nullable=True, comment='Primary email ID (references user_emails table)'),
    sa.Column('password_hash', sa.Text(), nullable=True, comment='Password hash using Argon2id (NULL for OAuth-only users - preferred)'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', name='user_status_enum'), server_default='ACTIVE', nullable=False, comment='User account status'),
    sa.Column('full_name', sa.Text(), nullable=True, comment="User's full name"),
    sa.Column('rut', sa.Text(), nullable=True, comment='Chilean RUT normalizado (formato: 12345678-9)'),
    sa.Column('address', sa.Text(), nullable=True, comment="User's residential address"),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.CheckConstraint("rut IS NULL OR rut ~ '^[0-9]{7,8}-[0-9Kk]$'", name='ck_user_rut_format'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('user_emails',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID for the email'),
    sa.Column('email', postgresql.CITEXT(), nullable=False, comment='Email address'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='Email verification timestamp'),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False, comment="Whether this is the user's primary email"),
    sa.Column('email_type', sa.String(length=20), server_default='personal', nullable=False, comment='Email type: personal, institutional, recovery'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.CheckConstraint("email_type IN ('personal', 'institutional', 'recovery')", name='ck_user_email_type'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id', 'email', name='uq_user_email'),
    schema='sistema_unidad_territorial'
    )
    # Add the foreign key from users to user_emails after both tables exist
    op.create_foreign_key(
        'fk_users_primary_email_id',
        'users', 'user_emails',
        ['primary_email_id'], ['id'],
        ondelete='SET NULL',
        source_schema='sistema_unidad_territorial',
        referent_schema='sistema_unidad_territorial'
    )
    op.create_table('address_evidences',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID for the evidence'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='Type of address evidence'),
    sa.Column('bucket', sa.Text(), nullable=False, comment='Bucket donde se almacena la evidencia'),
    sa.Column('storage_key', sa.Text(), nullable=False, comment='Clave de almacenamiento de la evidencia'),
    sa.Column('sha256', sa.String(length=64), nullable=False, comment='SHA256 hash del archivo'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='Tipo MIME del archivo'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant ID for multi-tenancy support (NOT NULL)'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.CheckConstraint("type IN ('utility_bill', 'rental_contract', 'other')", name='ck_evidence_type'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True, comment='User ID who performed the action'),
    sa.Column('action', sa.Text(), nullable=False, comment='Action performed'),
    sa.Column('entity', sa.Text(), nullable=False, comment='Type of entity affected'),
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='ID of the affected entity'),
    sa.Column('occurred_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Action timestamp'),
    sa.Column('actor_type', sa.String(length=20), nullable=True, comment='Type of actor: user, system'),
    sa.Column('request_id', sa.UUID(), nullable=True, comment='Request correlation ID'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional action metadata'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.CheckConstraint("actor_type IS NULL OR actor_type IN ('user', 'system')", name='ck_audit_log_actor_type'),
    sa.ForeignKeyConstraint(['actor_id'], ['sistema_unidad_territorial.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('certificates',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID for the certificate'),
    sa.Column('approver_id', sa.UUID(), nullable=True, comment='User ID who approved the certificate'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Certificate processing status'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Reason for rejection or observations'),
    sa.Column('folio', sa.Text(), nullable=False, comment='Certificate folio number'),
    sa.Column('pdf_bucket', sa.Text(), nullable=True, comment='Bucket donde se almacena el PDF'),
    sa.Column('pdf_storage_key', sa.Text(), nullable=True, comment='Clave de almacenamiento del PDF'),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True, comment='SHA256 hash del archivo PDF'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant ID for multi-tenancy support (NOT NULL)'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.CheckConstraint("pdf_sha256 IS NULL OR pdf_sha256 ~ '^[0-9a-f]{64}$'", name='ck_certificate_sha256_format'),
    sa.CheckConstraint("status IN ('CertificateStatus.PENDING', 'CertificateStatus.APPROVED', 'CertificateStatus.REJECTED', 'CertificateStatus.ISSUED')", name='ck_certificate_status'),
    sa.ForeignKeyConstraint(['approver_id'], ['sistema_unidad_territorial.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'folio', name='uq_certificate_tenant_folio'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('communities',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Municipality (tenant) ID that owns this community'),
    sa.Column('name', sa.Text(), nullable=False, comment="Community name (e.g., 'Junta Vecinos Villa Norte')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Community description'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.ForeignKeyConstraint(['tenant_id'], ['sistema_unidad_territorial.tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_community_tenant_name'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('notification_logs',
    sa.Column('outbox_id', sa.UUID(), nullable=True, comment='Outbox event that originated this notification'),
    sa.Column('type', sa.Text(), nullable=False, comment='Notification type'),
    sa.Column('destination', sa.Text(), nullable=False, comment='Destination (email, phone, etc.)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Delivery status'),
    sa.Column('provider_message_id', sa.Text(), nullable=True, comment="Provider's message ID for tracking"),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot of the payload at delivery time'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.CheckConstraint("status IN ('NotificationStatus.SENT', 'NotificationStatus.FAILED')", name='ck_notification_log_status'),
    sa.ForeignKeyConstraint(['outbox_id'], ['sistema_unidad_territorial.outbox.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Usuario que solicita el reset'),
    sa.Column('token', sa.Text(), nullable=False, comment='Token para URLs de reset'),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False, comment='Hash del token para validación segura'),
    sa.Column('expires_at', postgresql.TIMESTAMP(), nullable=False, comment='Fecha y hora de expiración del token'),
    sa.Column('consumed_at', postgresql.TIMESTAMP(), nullable=True, comment='Fecha y hora cuando se consumió el token'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User agent del navegador que solicitó el reset'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('role_assignments',
    sa.Column('role_id', sa.UUID(), nullable=False, comment='Role ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('scope_type', sa.String(length=20), nullable=False, comment='Tipo de scope: system, tenant, community'),
    sa.Column('scope_id', sa.UUID(), nullable=True, comment='ID del scope (NULL para system)'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant ID para coherencia (NULL solo para system)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.CheckConstraint("(scope_type = 'system' AND scope_id IS NULL AND tenant_id IS NULL) OR (scope_type IN ('tenant', 'community') AND scope_id IS NOT NULL AND tenant_id IS NOT NULL)", name='ck_role_assignment_scope_consistency'),
    sa.CheckConstraint("scope_type IN ('system', 'tenant', 'community')", name='ck_role_assignment_scope_type'),
    sa.ForeignKeyConstraint(['role_id'], ['sistema_unidad_territorial.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'scope_type', 'scope_id', name='uq_role_assignment_unique_per_scope'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('system_role_assignments',
    sa.Column('role_id', sa.UUID(), nullable=False, comment='Role ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.ForeignKeyConstraint(['role_id'], ['sistema_unidad_territorial.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'user_id', name='uq_system_role_assignment'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('tenant_role_assignments',
    sa.Column('role_id', sa.UUID(), nullable=False, comment='Role ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.ForeignKeyConstraint(['role_id'], ['sistema_unidad_territorial.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['sistema_unidad_territorial.tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'user_id', 'tenant_id', name='uq_tenant_role_assignment'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('user_oauth_identities',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID for the OAuth identity'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='OAuth provider (google, etc.)'),
    sa.Column('provider_user_id', sa.Text(), nullable=False, comment='User ID in the OAuth provider'),
    sa.Column('provider_email', postgresql.CITEXT(), nullable=True, comment='Email reported by the OAuth provider'),
    sa.Column('encrypted_access_token', sa.LargeBinary(), nullable=True, comment='OAuth access token cifrado'),
    sa.Column('encrypted_refresh_token', sa.LargeBinary(), nullable=True, comment='OAuth refresh token cifrado'),
    sa.Column('token_scope', sa.Text(), nullable=True, comment='OAuth token scope'),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True, comment='OAuth token expiration timestamp'),
    sa.Column('token_last_rotated_at', sa.DateTime(timezone=True), nullable=True, comment='Última rotación de tokens'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant ID for multi-tenancy support (NOT NULL)'),
    sa.CheckConstraint("provider IN ('google')", name='ck_oauth_provider'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_identity'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID for the session'),
    sa.Column('access_token_hash', sa.Text(), nullable=False, comment='SHA256 hash of the access token'),
    sa.Column('refresh_token_hash', sa.Text(), nullable=True, comment='SHA256 hash of the refresh token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Session expiration timestamp'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Client user agent string'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the session is active'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when session was revoked'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last session usage'),
    sa.Column('device_id', sa.Text(), nullable=True, comment='Device identifier'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant ID for multi-tenancy support (NOT NULL)'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('authentication_log',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='ID del usuario (NULL si no se pudo identificar)'),
    sa.Column('user_session_id', sa.UUID(), nullable=True, comment='ID de sesión creada en caso de éxito'),
    sa.Column('email', postgresql.CITEXT(), nullable=True, comment='Email utilizado en el intento (puede no existir como usuario)'),
    sa.Column('provider', sa.Enum('local', 'google', 'magic_link', name='auth_provider_enum'), nullable=False, comment='Proveedor de autenticación (local, google, magic_link)'),
    sa.Column('method', sa.Enum('password', 'oauth', 'magic_link', name='auth_method_enum'), nullable=False, comment='Método de autenticación (password, oauth, magic_link)'),
    sa.Column('result', sa.Enum('SUCCESS', 'FAIL', name='auth_result_enum'), nullable=False, comment='Resultado del intento (SUCCESS, FAIL)'),
    sa.Column('failure_reason', sa.Enum('INVALID_PASSWORD', 'INVALID_EMAIL', 'ACCOUNT_SUSPENDED', 'EMAIL_NOT_VERIFIED', 'OAUTH_ERROR', 'OAUTH_EMAIL_MISMATCH', 'TOKEN_EXPIRED', 'TOKEN_INVALID', 'RATE_LIMITED', 'ACCOUNT_LOCKED', 'MFA_REQUIRED', 'MFA_INVALID', 'UNKNOWN_ERROR', name='auth_failure_reason_enum'), nullable=True, comment='Razón específica del fallo'),
    sa.Column('error_code', sa.Text(), nullable=True, comment='Código de error interno del sistema'),
    sa.Column('mfa_used', sa.Boolean(), server_default='false', nullable=False, comment='Si se utilizó autenticación multifactor'),
    sa.Column('risk_score', sa.SmallInteger(), nullable=True, comment='Puntuación de riesgo calculada (0-100)'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User Agent del navegador/cliente'),
    sa.Column('request_id', sa.UUID(), nullable=True, comment='ID de correlación con logs de aplicación'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant ID for multi-tenancy support (NOT NULL)'),
    sa.CheckConstraint("(result = 'SUCCESS' AND failure_reason IS NULL) OR (result = 'FAIL')", name='ck_auth_log_success_no_failure_reason'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='ck_auth_log_risk_score_range'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_session_id'], ['sistema_unidad_territorial.user_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('community_role_assignments',
    sa.Column('role_id', sa.UUID(), nullable=False, comment='Role ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('community_id', sa.UUID(), nullable=False, comment='Community ID'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.ForeignKeyConstraint(['community_id'], ['sistema_unidad_territorial.communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sistema_unidad_territorial.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'user_id', 'community_id', name='uq_community_role_assignment'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('projects',
    sa.Column('community_id', sa.UUID(), nullable=False, comment='Community ID where the project is proposed'),
    sa.Column('requesting_user_id', sa.UUID(), nullable=False, comment='User ID who requested the project'),
    sa.Column('title', sa.Text(), nullable=False, comment='Project title'),
    sa.Column('description', sa.Text(), nullable=False, comment='Project description'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Project status'),
    sa.Column('observations', sa.Text(), nullable=True, comment='Project observations or notes'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.Column('lock_version', sa.Integer(), server_default='0', nullable=False, comment='Version for optimistic locking'),
    sa.CheckConstraint("status IN ('ProjectStatus.PENDING', 'ProjectStatus.IN_PROGRESS', 'ProjectStatus.COMPLETED', 'ProjectStatus.REJECTED')", name='ck_project_status'),
    sa.ForeignKeyConstraint(['community_id'], ['sistema_unidad_territorial.communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['sistema_unidad_territorial.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('registration_requests',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Municipality (tenant) ID'),
    sa.Column('community_id', sa.UUID(), nullable=False, comment='Community ID where user wants to register'),
    sa.Column('email', postgresql.CITEXT(), nullable=False, comment='Applicant email address'),
    sa.Column('full_name', sa.Text(), nullable=True, comment='Applicant full name'),
    sa.Column('rut', sa.Text(), nullable=True, comment='Chilean RUT (optional at submission; validated on approval)'),
    sa.Column('address', sa.Text(), nullable=True, comment='Applicant address'),
    sa.Column('provider', sa.Enum('local', 'google', 'magic_link', name='registration_provider_enum'), nullable=False, comment='Authentication provider'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_CHANGES', name='registration_status_enum'), server_default='PENDING', nullable=False, comment='Request status'),
    sa.Column('decided_by', sa.UUID(), nullable=True, comment='Moderator who made the decision'),
    sa.Column('decided_at', postgresql.TIMESTAMP(), nullable=True, comment='Decision timestamp'),
    sa.Column('expires_at', postgresql.TIMESTAMP(), nullable=True, comment='Request expiration timestamp'),
    sa.Column('decision_notes', sa.Text(), nullable=True, comment='Notes from the moderator decision'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.ForeignKeyConstraint(['community_id'], ['sistema_unidad_territorial.communities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decided_by'], ['sistema_unidad_territorial.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['sistema_unidad_territorial.tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('resident_memberships',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID for the membership'),
    sa.Column('community_id', sa.UUID(), nullable=False, comment='Community ID for the membership'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_CHANGES', name='membership_status_enum'), nullable=False, comment='Membership status'),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False, comment='Whether the membership is verified'),
    sa.Column('verified_at', postgresql.TIMESTAMP(), nullable=True, comment='Verification timestamp'),
    sa.Column('verified_by', sa.UUID(), nullable=True, comment='User who verified the membership'),
    sa.Column('verification_method', sa.String(length=50), nullable=True, comment='Method used for verification'),
    sa.Column('board_role', sa.Enum('president', 'secretary', 'treasurer', 'vocal', name='board_role_enum'), nullable=True, comment='Board role if member is part of community governance'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.ForeignKeyConstraint(['community_id'], ['sistema_unidad_territorial.communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['sistema_unidad_territorial.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'community_id', name='uq_membership_user_community'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('spaces',
    sa.Column('community_id', sa.UUID(), nullable=False, comment='Community ID that owns this space'),
    sa.Column('name', sa.Text(), nullable=False, comment='Space name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Space description'),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='Maximum capacity'),
    sa.Column('requires_approval', sa.Boolean(), server_default='true', nullable=False, comment='Whether reservations require approval'),
    sa.Column('rules_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True, comment='Space rules and restrictions'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.ForeignKeyConstraint(['community_id'], ['sistema_unidad_territorial.communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('project_attachments',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Project ID for the attachment'),
    sa.Column('bucket', sa.Text(), nullable=False, comment='Bucket donde se almacena el archivo'),
    sa.Column('storage_key', sa.Text(), nullable=False, comment='Clave de almacenamiento del archivo'),
    sa.Column('sha256', sa.String(length=64), nullable=False, comment='SHA256 hash del archivo'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='Tipo MIME del archivo'),
    sa.Column('original_filename', sa.Text(), nullable=True, comment='Nombre original del archivo'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.ForeignKeyConstraint(['project_id'], ['sistema_unidad_territorial.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('registration_request_attachments',
    sa.Column('registration_request_id', sa.UUID(), nullable=False, comment='Registration request ID'),
    sa.Column('bucket', sa.Text(), nullable=False, comment='Bucket donde se almacena el archivo'),
    sa.Column('storage_key', sa.Text(), nullable=False, comment='Clave de almacenamiento del archivo'),
    sa.Column('sha256', sa.String(length=64), nullable=False, comment='SHA256 hash del archivo'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='Tipo MIME del archivo'),
    sa.Column('kind', sa.Enum('id_card_front', 'id_card_back', 'utility_bill', 'rent_contract', 'other', name='attachment_kind_enum'), nullable=False, comment='Type of attachment'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.ForeignKeyConstraint(['registration_request_id'], ['sistema_unidad_territorial.registration_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('reservations',
    sa.Column('space_id', sa.UUID(), nullable=False, comment='Space ID for the reservation'),
    sa.Column('requesting_user_id', sa.UUID(), nullable=False, comment='User ID who made the reservation'),
    sa.Column('start_time', postgresql.TIMESTAMP(), nullable=False, comment='Reservation start time'),
    sa.Column('end_time', postgresql.TIMESTAMP(), nullable=False, comment='Reservation end time'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Reservation status'),
    sa.Column('canceled_at', postgresql.TIMESTAMP(), nullable=True, comment='Cancellation timestamp'),
    sa.Column('cancel_reason', sa.Text(), nullable=True, comment='Reason for cancellation'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp with timezone'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='Soft delete timestamp - NULL means active'),
    sa.CheckConstraint("status IN ('ReservationStatus.PENDING', 'ReservationStatus.CONFIRMED', 'ReservationStatus.CANCELLED')", name='ck_reservation_status'),
    sa.CheckConstraint('end_time > start_time', name='ck_reservation_end_after_start'),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['sistema_unidad_territorial.users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['space_id'], ['sistema_unidad_territorial.spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations', schema='sistema_unidad_territorial')
    op.drop_table('registration_request_attachments', schema='sistema_unidad_territorial')
    op.drop_table('project_attachments', schema='sistema_unidad_territorial')
    op.drop_table('spaces', schema='sistema_unidad_territorial')
    op.drop_table('resident_memberships', schema='sistema_unidad_territorial')
    op.drop_table('registration_requests', schema='sistema_unidad_territorial')
    op.drop_table('projects', schema='sistema_unidad_territorial')
    op.drop_table('community_role_assignments', schema='sistema_unidad_territorial')
    op.drop_table('authentication_log', schema='sistema_unidad_territorial')
    op.drop_table('user_sessions', schema='sistema_unidad_territorial')
    op.drop_table('user_oauth_identities', schema='sistema_unidad_territorial')
    op.drop_table('tenant_role_assignments', schema='sistema_unidad_territorial')
    op.drop_table('system_role_assignments', schema='sistema_unidad_territorial')
    op.drop_table('role_assignments', schema='sistema_unidad_territorial')
    op.drop_table('password_reset_tokens', schema='sistema_unidad_territorial')
    op.drop_table('notification_logs', schema='sistema_unidad_territorial')
    op.drop_table('communities', schema='sistema_unidad_territorial')
    op.drop_table('certificates', schema='sistema_unidad_territorial')
    op.drop_table('audit_logs', schema='sistema_unidad_territorial')
    op.drop_table('address_evidences', schema='sistema_unidad_territorial')
    op.drop_constraint('fk_users_primary_email_id', 'users', schema='sistema_unidad_territorial')
    op.drop_table('user_emails', schema='sistema_unidad_territorial')
    op.drop_table('users', schema='sistema_unidad_territorial')
    op.drop_table('tenants', schema='sistema_unidad_territorial')
    op.drop_table('tenant_folio_seq', schema='sistema_unidad_territorial')
    op.drop_table('status_reservation', schema='sistema_unidad_territorial')
    op.drop_table('status_registration', schema='sistema_unidad_territorial')
    op.drop_table('status_project', schema='sistema_unidad_territorial')
    op.drop_table('status_membership', schema='sistema_unidad_territorial')
    op.drop_table('status_certificate', schema='sistema_unidad_territorial')
    op.drop_table('roles', schema='sistema_unidad_territorial')
    op.drop_table('outbox', schema='sistema_unidad_territorial')
    op.drop_table('news', schema='sistema_unidad_territorial')
    # ### end Alembic commands ###
