"""mensaje

Revision ID: 909daa43825e
Revises: de8f2bb2da24
Create Date: 2025-11-11 01:58:37.092082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909daa43825e'
down_revision: Union[str, Sequence[str], None] = 'de8f2bb2da24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('code', sa.Text(), nullable=False, comment='Código de 6 dígitos para validación'), schema='sistema_unidad_territorial')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_tokens', 'code', schema='sistema_unidad_territorial')
    # ### end Alembic commands ###
