"""First Revision

Revision ID: ae803eefd5c6
Revises: 
Create Date: 2025-08-17 23:44:53.194852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae803eefd5c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('title', sa.Text(), nullable=False, comment='News title'),
    sa.Column('body', sa.Text(), nullable=False, comment='News content'),
    sa.Column('visible_from', sa.DateTime(timezone=True), nullable=False, comment='Start of visibility period'),
    sa.Column('visible_until', sa.DateTime(timezone=True), nullable=True, comment='End of visibility period (optional)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant ID for multi-tenancy support'),
    sa.CheckConstraint('visible_until IS NULL OR visible_until > visible_from', name='ck_news_valid_dates'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('notification_logs',
    sa.Column('type', sa.Text(), nullable=False, comment='Notification type'),
    sa.Column('destination', sa.Text(), nullable=False, comment='Destination (email, phone, etc.)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Delivery status'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.CheckConstraint("status IN ('NotificationStatus.SENT', 'NotificationStatus.FAILED')", name='ck_notification_log_status'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('outbox',
    sa.Column('type', sa.Text(), nullable=False, comment='Message type: email, whatsapp, webhook, etc.'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Message data'),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False, comment='Number of delivery attempts'),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True, comment='Next delivery attempt timestamp'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.CheckConstraint("jsonb_typeof(payload) = 'object'", name='ck_outbox_payload_object'),
    sa.CheckConstraint("payload ? 'to'", name='ck_outbox_payload_has_to'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Role name'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('spaces',
    sa.Column('name', sa.Text(), nullable=False, comment='Space name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Space description'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant ID for multi-tenancy support'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('tenants',
    sa.Column('name', sa.Text(), nullable=False, comment='Tenant name'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=True, comment='User email (can be NULL for OAuth-only users)'),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True, comment='Email verification timestamp'),
    sa.Column('password_hash', sa.Text(), nullable=True, comment='Password hash (NULL for OAuth-only users)'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', name='user_status_enum'), server_default='ACTIVE', nullable=False, comment='User account status'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True, comment='User ID who performed the action'),
    sa.Column('action', sa.Text(), nullable=False, comment='Action performed'),
    sa.Column('entity', sa.Text(), nullable=False, comment='Type of entity affected'),
    sa.Column('entity_id', sa.UUID(), nullable=False, comment='ID of the affected entity'),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='IP address of the actor'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Action timestamp'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional action metadata'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.ForeignKeyConstraint(['actor_id'], ['sistema_unidad_territorial.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('auth_magic_links',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID for the magic link'),
    sa.Column('token_hash', sa.Text(), nullable=False, comment='Hashed authentication token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Magic link expiration timestamp'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the link was used'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('residents',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Associated user ID (optional)'),
    sa.Column('rut', sa.String(length=15), nullable=False, comment='Chilean RUT (national ID)'),
    sa.Column('name', sa.Text(), nullable=False, comment='Full name of the resident'),
    sa.Column('address', sa.Text(), nullable=False, comment='Complete address'),
    sa.Column('neighborhood_unit', sa.Text(), nullable=True, comment='Neighborhood unit (UV - Unidad Vecinal)'),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False, comment='Whether the resident is verified'),
    sa.Column('registration_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False, comment='Date when the resident was registered'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant ID for multi-tenancy support'),
    sa.CheckConstraint("rut ~ '^[0-9]{1,2}\\.?[0-9]{3}\\.?[0-9]{3}-[0-9kK]{1}$'", name='ck_resident_rut_format'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('user_oauth_identities',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID for the OAuth identity'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='OAuth provider (google, etc.)'),
    sa.Column('provider_user_id', sa.Text(), nullable=False, comment='User ID in the OAuth provider'),
    sa.Column('provider_email', postgresql.CITEXT(), nullable=True, comment='Email reported by the OAuth provider'),
    sa.Column('access_token', sa.Text(), nullable=True, comment='OAuth access token'),
    sa.Column('refresh_token', sa.Text(), nullable=True, comment='OAuth refresh token'),
    sa.Column('token_scope', sa.Text(), nullable=True, comment='OAuth token scope'),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True, comment='OAuth token expiration timestamp'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.CheckConstraint("provider IN ('OAuthProvider.GOOGLE')", name='ck_oauth_provider'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_identity'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sistema_unidad_territorial.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID for the session'),
    sa.Column('access_token_hash', sa.Text(), nullable=False, comment='SHA256 hash of the access token'),
    sa.Column('refresh_token_hash', sa.Text(), nullable=True, comment='SHA256 hash of the refresh token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Session expiration timestamp'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address (IPv4 or IPv6)'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Client user agent string'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the session is active'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when session was revoked'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.ForeignKeyConstraint(['user_id'], ['sistema_unidad_territorial.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('address_evidences',
    sa.Column('resident_id', sa.UUID(), nullable=False, comment='Resident ID for the evidence'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='Type of address evidence'),
    sa.Column('url', sa.Text(), nullable=False, comment='URL of the evidence file'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant ID for multi-tenancy support'),
    sa.CheckConstraint("type IN ('EvidenceType.UTILITY_BILL', 'EvidenceType.RENTAL_CONTRACT', 'EvidenceType.OTHER')", name='ck_evidence_type'),
    sa.ForeignKeyConstraint(['resident_id'], ['sistema_unidad_territorial.residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('certificates',
    sa.Column('resident_id', sa.UUID(), nullable=False, comment='Resident ID for the certificate'),
    sa.Column('approver_id', sa.UUID(), nullable=True, comment='User ID who approved the certificate'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Certificate processing status'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Reason for rejection or observations'),
    sa.Column('folio', sa.Text(), nullable=False, comment='Certificate folio number'),
    sa.Column('pdf_url', sa.Text(), nullable=True, comment='URL of the generated PDF certificate'),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True, comment='SHA256 hash of the PDF file'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant ID for multi-tenancy support'),
    sa.CheckConstraint("pdf_sha256 IS NULL OR pdf_sha256 ~ '^[0-9a-f]{64}$'", name='ck_certificate_sha256_format'),
    sa.CheckConstraint("status IN ('CertificateStatus.PENDING', 'CertificateStatus.APPROVED', 'CertificateStatus.REJECTED', 'CertificateStatus.ISSUED')", name='ck_certificate_status'),
    sa.ForeignKeyConstraint(['approver_id'], ['sistema_unidad_territorial.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['sistema_unidad_territorial.residents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'folio', name='uq_certificate_tenant_folio'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('projects',
    sa.Column('requesting_resident_id', sa.UUID(), nullable=False, comment='Resident ID who requested the project'),
    sa.Column('title', sa.Text(), nullable=False, comment='Project title'),
    sa.Column('description', sa.Text(), nullable=False, comment='Project description'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Project status'),
    sa.Column('observations', sa.Text(), nullable=True, comment='Project observations or notes'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant ID for multi-tenancy support'),
    sa.CheckConstraint("status IN ('ProjectStatus.PENDING', 'ProjectStatus.IN_PROGRESS', 'ProjectStatus.COMPLETED', 'ProjectStatus.REJECTED')", name='ck_project_status'),
    sa.ForeignKeyConstraint(['requesting_resident_id'], ['sistema_unidad_territorial.residents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('reservations',
    sa.Column('space_id', sa.UUID(), nullable=False, comment='Space ID for the reservation'),
    sa.Column('requesting_resident_id', sa.UUID(), nullable=False, comment='Resident ID who made the reservation'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Reservation start time'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='Reservation end time'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Reservation status'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant ID for multi-tenancy support'),
    sa.CheckConstraint("status IN ('ReservationStatus.PENDING', 'ReservationStatus.CONFIRMED', 'ReservationStatus.CANCELLED')", name='ck_reservation_status'),
    sa.CheckConstraint('end_time > start_time', name='ck_reservation_end_after_start'),
    sa.ForeignKeyConstraint(['requesting_resident_id'], ['sistema_unidad_territorial.residents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['space_id'], ['sistema_unidad_territorial.spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    op.create_table('project_attachments',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Project ID for the attachment'),
    sa.Column('url', sa.Text(), nullable=False, comment='URL of the attachment file'),
    sa.Column('type', sa.Text(), nullable=False, comment='Type of the attachment file'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp in Chile timezone'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp in Chile timezone'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant ID for multi-tenancy support'),
    sa.ForeignKeyConstraint(['project_id'], ['sistema_unidad_territorial.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sistema_unidad_territorial'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_attachments', schema='sistema_unidad_territorial')
    op.drop_table('reservations', schema='sistema_unidad_territorial')
    op.drop_table('projects', schema='sistema_unidad_territorial')
    op.drop_table('certificates', schema='sistema_unidad_territorial')
    op.drop_table('address_evidences', schema='sistema_unidad_territorial')
    op.drop_table('user_sessions', schema='sistema_unidad_territorial')
    op.drop_table('user_roles', schema='sistema_unidad_territorial')
    op.drop_table('user_oauth_identities', schema='sistema_unidad_territorial')
    op.drop_table('residents', schema='sistema_unidad_territorial')
    op.drop_table('auth_magic_links', schema='sistema_unidad_territorial')
    op.drop_table('audit_logs', schema='sistema_unidad_territorial')
    op.drop_table('users', schema='sistema_unidad_territorial')
    op.drop_table('tenants', schema='sistema_unidad_territorial')
    op.drop_table('spaces', schema='sistema_unidad_territorial')
    op.drop_table('roles', schema='sistema_unidad_territorial')
    op.drop_table('outbox', schema='sistema_unidad_territorial')
    op.drop_table('notification_logs', schema='sistema_unidad_territorial')
    op.drop_table('news', schema='sistema_unidad_territorial')
    # ### end Alembic commands ###
