"""fix enum reservation

Revision ID: de8f2bb2da24
Revises: da976fa03a89
Create Date: 2025-11-07 10:45:45.553732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de8f2bb2da24'
down_revision: Union[str, Sequence[str], None] = 'da976fa03a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_registration', schema='sistema_unidad_territorial')
    op.drop_table('status_project', schema='sistema_unidad_territorial')
    op.drop_table('status_reservation', schema='sistema_unidad_territorial')
    op.drop_table('status_membership', schema='sistema_unidad_territorial')
    op.drop_table('status_certificate', schema='sistema_unidad_territorial')
    op.drop_table('tenant_folio_seq', schema='sistema_unidad_territorial')
    # ### end Alembic commands ###

    # Corregir constraint de status en tabla reservations
    # Eliminar el constraint viejo si existe
    op.execute("""
        ALTER TABLE sistema_unidad_territorial.reservations 
        DROP CONSTRAINT IF EXISTS ck_reservation_status;
    """)

    # Crear el nuevo constraint con los valores string correctos
    op.execute("""
        ALTER TABLE sistema_unidad_territorial.reservations 
        ADD CONSTRAINT ck_reservation_status 
        CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED'));
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Revertir el constraint de status en tabla reservations
    op.execute("""
        ALTER TABLE sistema_unidad_territorial.reservations 
        DROP CONSTRAINT IF EXISTS ck_reservation_status;
    """)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_folio_seq',
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID del tenant'),
    sa.Column('last_folio', sa.INTEGER(), autoincrement=False, nullable=False, comment='Último folio emitido'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Last update timestamp with timezone'),
    sa.ForeignKeyConstraint(['tenant_id'], ['sistema_unidad_territorial.tenants.id'], name=op.f('tenant_folio_seq_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'id', name=op.f('tenant_folio_seq_pkey')),
    schema='sistema_unidad_territorial'
    )
    op.create_table('status_certificate',
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Código del estado de certificado'),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Nombre descriptivo del estado'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Descripción del estado'),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False, comment='Orden de visualización'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Last update timestamp with timezone'),
    sa.PrimaryKeyConstraint('code', 'id', name=op.f('status_certificate_pkey')),
    schema='sistema_unidad_territorial'
    )
    op.create_table('status_membership',
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Código del estado de membresía'),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Nombre descriptivo del estado'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Descripción del estado'),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False, comment='Orden de visualización'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Last update timestamp with timezone'),
    sa.PrimaryKeyConstraint('code', 'id', name=op.f('status_membership_pkey')),
    schema='sistema_unidad_territorial'
    )
    op.create_table('status_reservation',
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Código del estado de reserva'),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Nombre descriptivo del estado'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Descripción del estado'),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False, comment='Orden de visualización'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Last update timestamp with timezone'),
    sa.PrimaryKeyConstraint('code', 'id', name=op.f('status_reservation_pkey')),
    schema='sistema_unidad_territorial'
    )
    op.create_table('status_project',
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Código del estado de proyecto'),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Nombre descriptivo del estado'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Descripción del estado'),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False, comment='Orden de visualización'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Last update timestamp with timezone'),
    sa.PrimaryKeyConstraint('code', 'id', name=op.f('status_project_pkey')),
    schema='sistema_unidad_territorial'
    )
    op.create_table('status_registration',
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Código del estado de solicitud de registro'),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Nombre descriptivo del estado'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Descripción del estado'),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False, comment='Orden de visualización'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Creation timestamp with timezone'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Last update timestamp with timezone'),
    sa.PrimaryKeyConstraint('code', 'id', name=op.f('status_registration_pkey')),
    schema='sistema_unidad_territorial'
    )
    # ### end Alembic commands ###
